### ISSUE TITLE
npm install @hapi/bourne fails,npm registry returns {"error":"Not found"}

### ISSUE THREAD

**Issue by xoryouyou** [hapijs/bourne#19]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: v14.7.0
* *module version*: v2.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):pino-pretty
* *any other relevant information*:

#### How can we help?

When I run `npm i @hapi/bourne ` npm fails since it tries to fetch `@hapi/bourne@latest`  but  https://registry.npmjs.org/@hapi%2fbourne returns `{"error":"Not found"}`.
![2020-08-06_11-25-26](https://user-images.githubusercontent.com/777569/89516128-552ad680-d7d8-11ea-86f4-c50d06cf4baf.png)

Since npm is working for other packages I thought I'll directly report it to you.

The module I am trying to install which depends on bourne is `pino-pretty` https://github.com/pinojs/pino-pretty/blob/master/package.json#L32

**Comment by nemo347** [comment]
Maybe related to https://github.com/npm/cli/issues/1624

**Comment by xoryouyou** [comment]
Oh right. I seemed to be lucky that the rest of my `package.json` installed completely fine. 

Will take the Issue over  to npm but thanks none the less. :+1:
