### ISSUE TITLE
consider constructor.prototype harmful?

### ISSUE THREAD

**Issue by dwelle** [hapijs/bourne#6]
I've noticed another pattern for prototype poisoning which isn't exactly related to JSON parsing, but may be interesting from the viewpoint of this library nonetheless, since people may start to regard this library as "something that returns parsed JSON that can be safely assigned/merged with other objects". If I got a mistaken impression, feel free to close.

An object that looks like this: `{ "constructor": { "prototype": { "danger": 42 } } }`, if later deeply merged using some unsafe technique will end up poisoning the prototype.

E.g., using an older `lodash`, or custom, poorly written deep-merge helper.

(note: as stated above, the JSON parse step is redundant, but I included the step so as to show what people may end up doing).

```js
const bourne = require("bourne"); // @1.1.1
const _ = require("lodash"); // @4.17.10
const polluted = bourne.parse(`{ "constructor": { "prototype": { "danger": 42 } } }`);
_.merge({}, polluted);
console.log(({}).danger); // 42
```

or

```js
const bourne = require("bourne"); // @1.1.1

function isPlainObject ( val ) {
    return typeof val == 'object' && val.constructor == Object;
}
// purposefully incorrect implem
function merge ( a, b ) {
    for ( const key in b ) {
        const val = b[key];
        if ( isPlainObject(val) ) {
            a[key] = merge(a[key], val)
        } else {
            a[key] = val;
        }
    }
    return a;
}

const polluted = bourne.parse(`{ "constructor": { "prototype": { "danger": 42 } } }`);
merge({}, polluted);
console.log(({}).danger); // 42
```

Lodash has since [fixed the `_.merge` behavior](https://github.com/lodash/lodash/commit/90e6199a161b6445b01454517b40ef65ebecd2ad) (which is how I learned about this), but other userland code may still/will be affected.

I guess it comes down to how much `bourne` is trying to play on police.

**Comment by hueniverse** [comment]
This is excessive for bourne. At some point people are responsible for their own code. If you are going to do something stupid with unvalidated objects, it's on you.
