### ISSUE TITLE
Change module namespace

### ISSUE THREAD

**Issue by hueniverse** [hapijs/bourne#8]

**Comment by mcollina** [comment]
Essentially this module will now move in the hapi namespace? I guess this is related to make Hapi sustainable, have you got some details / is this documented somewhere?

I thought this module was thought as an utility for the community, rather than something hapi-specific

**Comment by hueniverse** [comment]
Expect a blog post next few days, before you start seeing deprecation warnings...

TL;DR everything is moving to a namespace. People will just need to add `@hapi/` in front on this and otherwise will see no changes. Nothing prevents you from using `@hapi/` module outside of hapi. This is not the first community to move its modules to a namespace.

That said, if it bothers you, feel free to fork and I'll give you npm ownership over the deprecated name. I am not offering that for any other hapi module moving, but in this case, I am willing to make an exception.

**Comment by mcollina** [comment]
> Expect a blog post next few days, before you start seeing deprecation warnings...

Thanks! I _think_ I understand why you are doing this, 👍. Good idea, it will be a nice way to offer the paid support.

Are Joy and Lab moving as well?

**Comment by hueniverse** [comment]
This is not really about paid support. It is more about administration logistics and attribution. Everything is moving to a namespace. If it is under the GitHub hapi org, it is moving to the npm org.
